### ISSUE TITLE
[Question] How to finetune the SAC to get an expert

### ISSUE THREAD

**Issue by dibbla** [kevinzakka/x-magical#4]
Hi @kevinzakka 

Thank you for providing this inspiring environment!

I can see that in X-IRL, you used a modified version from [denisyarats](https://github.com/denisyarats/pytorch_sac). The `sac/` in X-IRL repo is actually not complete, so I tried to train with the original SAC implemetation on a simple setting `SweepToTop-Gripper-State-Allo-Demo-v0`.  However, I find it just doesn't work since the agent fail to continue the task after putting one block in the right place.

Do you have any hint about fine-tuning the SAC agent?

Btw, this is the configuration I'm using for training 5M timesteps:

```yaml
agent:
  name: sac
  class: agent.sac.SACAgent
  params:
    obs_dim: ??? # to be specified later
    action_dim: ??? # to be specified later
    action_range: ??? # to be specified later
    device: ${device}
    critic_cfg: ${double_q_critic}
    actor_cfg: ${diag_gaussian_actor}
    discount: 0.99
    init_temperature: 0.1 # 0.1
    alpha_lr: 1e-4
    alpha_betas: [0.9, 0.999]
    actor_lr: 1e-4
    actor_betas: [0.9, 0.999]
    actor_update_frequency: 1
    critic_lr: 1e-4
    critic_betas: [0.9, 0.999]
    critic_tau: 0.005
    critic_target_update_frequency: 2
    batch_size: 1024
    learnable_temperature: true
    
double_q_critic:
  class: agent.critic.DoubleQCritic
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_dim: 1024
    hidden_depth: 12
    
diag_gaussian_actor:
  class: agent.actor.DiagGaussianActor
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_depth: 12
    hidden_dim: 1024
    log_std_bounds: [-5, 2]
``` 

Thank you very much!
